USE DATABASE bwdncann_dev;

CREATE TABLE IF NOT EXISTS `users` (
    `ID_USER` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `IS_ADMIN` TINYINT(1) NOT NULL DEFAULT 0,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_USER`),
    UNIQUE KEY `UK_USERS_EMAIL` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `users_pwd_reset` (
    `ID_RESET` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_USER` INT UNSIGNED NOT NULL,
    `SELECTOR` VARCHAR(255) NOT NULL,
    `TOKEN_HASH` VARCHAR(255) NOT NULL,
    `EXPIRES_AT` DATETIME NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_RESET`),
    UNIQUE KEY `UK_PWDRESET_SELECTOR` (`SELECTOR`),
    KEY `IDX_PWDRESET_USER` (`ID_USER`),
    CONSTRAINT `FK_PWDRESET_USER`
        FOREIGN KEY (`ID_USER`) REFERENCES `users`(`ID_USER`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `customers` (
    `ID_CUSTOMER` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(50) NOT NULL,
    `LAST_NAME` VARCHAR(50) NOT NULL,
    `BALANCE` DECIMAL(12,2) NOT NULL DEFAULT 0,
    `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`ID_CUSTOMER`),
    UNIQUE KEY `UK_NAME` (`FIRST_NAME`, `LAST_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `users_customers` (
    `ID_USER` INT UNSIGNED NOT NULL,
    `ID_CUSTOMER` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`ID_USER`, `ID_CUSTOMER`),
    CONSTRAINT `FK_UC_USER`
        FOREIGN KEY (`ID_USER`) REFERENCES `users`(`ID_USER`)
        ON DELETE CASCADE,
    CONSTRAINT `FK_UC_CUSTOMER`
        FOREIGN KEY (`ID_CUSTOMER`) REFERENCES `customers`(`ID_CUSTOMER`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ref_topup_type` (
    `ID_TOPUP_TYPE` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID_TOPUP_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `ref_topup_type` (`NAME`) VALUES
    ('Initial'),
    ('Cash'),
    ('SumUp'),
    ('Refund'),
    ('Bank Transfer');

CREATE TABLE IF NOT EXISTS `ref_product` (
    `ID_PRODUCT` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100) NOT NULL,
    `PRICE` DECIMAL(10,2) NOT NULL,
    `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`ID_PRODUCT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `ref_product` (`NAME`, `PRICE`) VALUES
    ('Beer', 2.00),
    ('Cocktail', 3.00),
    ('Soft', 2.00),
    ('Peanuts', 1.00),
    ('Saucisson', 5.00);

CREATE TABLE IF NOT EXISTS `transactions` (
    `ID_TRANSACTION` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_USER` INT UNSIGNED NOT NULL,     -- admin who performed the transcation
    `ID_CUSTOMER` INT UNSIGNED NOT NULL, -- customer who ordered a drink
    `ID_PRODUCT` INT UNSIGNED NOT NULL,
    `QUANTITY` INT NOT NULL,
    `TOTAL` DECIMAL(10,2) NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_TRANSACTION`),
    KEY `IDX_TRANS_USER` (`ID_USER`),
    KEY `IDX_TRANS_CUSTOMER` (`ID_CUSTOMER`),
    KEY `IDX_TRANS_PRODUCT` (`ID_PRODUCT`),
    CONSTRAINT `FK_TRANS_USER`
        FOREIGN KEY (`ID_USER`) REFERENCES `users`(`ID_USER`),
    CONSTRAINT `FK_TRANS_CUSTOMER`
        FOREIGN KEY (`ID_CUSTOMER`) REFERENCES `customers`(`ID_CUSTOMER`),
    CONSTRAINT `FK_TRANS_PRODUCT`
        FOREIGN KEY (`ID_PRODUCT`) REFERENCES `ref_product`(`ID_PRODUCT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `wallet_topup` (
    `ID_TOPUP` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_USER` INT UNSIGNED NOT NULL,          
    `ID_CUSTOMER` INT UNSIGNED NOT NULL,      
    `ID_TOPUP_TYPE` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `AMOUNT` DECIMAL(10,2) NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_TOPUP`),
    KEY `IDX_WALLET_TOPUP_USER` (`ID_USER`),
    KEY `IDX_WALLET_TOPUP_CUSTOMER` (`ID_CUSTOMER`),
    KEY `IDX_WALLET_TOPUP_TYPE` (`ID_TOPUP_TYPE`),
    CONSTRAINT `FK_WALLET_TOPUP_USER`
        FOREIGN KEY (`ID_USER`) REFERENCES `users`(`ID_USER`)
        ON DELETE CASCADE,
    CONSTRAINT `FK_WALLET_TOPUP_CUSTOMER`
        FOREIGN KEY (`ID_CUSTOMER`) REFERENCES `customers`(`ID_CUSTOMER`)
        ON DELETE CASCADE,
    CONSTRAINT `FK_WALLET_TOPUP_TYPE`
        FOREIGN KEY (`ID_TOPUP_TYPE`) REFERENCES `ref_topup_type`(`ID_TOPUP_TYPE`)
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `purchases` (
    `PURCHASE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_USER` INT UNSIGNED NOT NULL,
    `COMMENT` VARCHAR(100) DEFAULT NULL,
    `AMOUNT` DECIMAL(12, 2) NOT NULL,
    `RECEIPT_PATH` VARCHAR(255) DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`PURCHASE_ID`),
    KEY `IDX_PURCHASES_USER` (`ID_USER`),
    CONSTRAINT `FK_PURCHASES_USER`
        FOREIGN KEY (`ID_USER`) REFERENCES `users`(`ID_USER`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE OR REPLACE VIEW v_master_transactions AS
    SELECT
        CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER,
        t.AMOUNT AS AMOUNT,
        r.NAME AS LABEL,
        t.CREATED_AT,
        CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME) AS BY_NAME
    FROM wallet_topup t
    JOIN customers c ON t.ID_CUSTOMER = c.ID_CUSTOMER
    LEFT JOIN users_customers uc ON t.ID_USER = uc.ID_USER
    LEFT JOIN customers a ON uc.ID_CUSTOMER = a.ID_CUSTOMER
    LEFT JOIN ref_topup_type r ON t.ID_TOPUP_TYPE = r.ID_TOPUP_TYPE
    UNION
    SELECT
        CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER,
        -(p.PRICE * tr.QUANTITY) AS AMOUNT,
        CONCAT(tr.QUANTITY, 'x', p.NAME) AS LABEL,
        tr.CREATED_AT,
        CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME) AS BY_NAME
    FROM transactions tr
    JOIN customers c ON tr.ID_CUSTOMER = c.ID_CUSTOMER
    LEFT JOIN users_customers uc ON tr.ID_USER = uc.ID_USER
    LEFT JOIN customers a ON uc.ID_CUSTOMER = a.ID_CUSTOMER
    LEFT JOIN ref_product p ON tr.ID_PRODUCT = p.ID_PRODUCT
    UNION
    SELECT
        ' -Amikale' AS CUSTOMER,
        -p.AMOUNT,
        p.COMMENT AS LABEL,
        p.CREATED_AT,
        CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME) AS BY_NAME
    FROM purchases p
    LEFT JOIN users_customers uc ON p.ID_USER = uc.ID_USER
    LEFT JOIN customers a ON uc.ID_CUSTOMER = a.ID_CUSTOMER
    ORDER BY CREATED_AT DESC, CUSTOMER, LABEL;

CREATE OR REPLACE VIEW v_cash_flow AS
    SELECT
        CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER,
        t.AMOUNT AS AMOUNT,
        r.NAME AS LABEL,
        t.CREATED_AT,
        CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME) AS BY_NAME
    FROM wallet_topup t
    JOIN customers c ON t.ID_CUSTOMER = c.ID_CUSTOMER
    LEFT JOIN users_customers uc ON t.ID_USER = uc.ID_USER
    LEFT JOIN customers a ON uc.ID_CUSTOMER = a.ID_CUSTOMER
    LEFT JOIN ref_topup_type r ON t.ID_TOPUP_TYPE = r.ID_TOPUP_TYPE
    WHERE t.ID_TOPUP_TYPE IN (2, 3, 6)
    UNION
    SELECT
        ' -Amikale' AS CUSTOMER,
        -p.AMOUNT,
        p.COMMENT AS LABEL,
        p.CREATED_AT,
        CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME) AS BY_NAME
    FROM purchases p
    LEFT JOIN users_customers uc ON p.ID_USER = uc.ID_USER
    LEFT JOIN customers a ON uc.ID_CUSTOMER = a.ID_CUSTOMER
    ORDER BY CREATED_AT DESC, CUSTOMER, LABEL;